#!/usr/bin/env node

import * as fs from "fs";
import * as path from "path";

const SOLUTIONS: Record<string, { title: string; template: string }> = {
  "medical-translation": {
    title: "医患语言无障碍翻译助手",
    template: "medical-translation",
  },
  "pmp-agent": {
    title: "医院 PMP 项目管理智能体",
    template: "pmp-agent",
  },
  "manufacturing-inspection": {
    title: "制造业设备巡检 AI 助手",
    template: "manufacturing-inspection",
  },
};

function parseArgs(argv: string[]) {
  const args: Record<string, string> = {};
  let command = "";
  let slug = "";

  for (let i = 2; i < argv.length; i++) {
    const arg = argv[i];
    if (arg.startsWith("--")) {
      const [key, val] = arg.slice(2).split("=");
      args[key] = val ?? "true";
    } else if (!command) {
      command = arg;
    } else if (!slug) {
      slug = arg;
    }
  }

  return { command, slug, args };
}

function listSolutions() {
  console.log("\n📦 Mland AI 解决方案\n");
  for (const [slug, meta] of Object.entries(SOLUTIONS)) {
    console.log(`  ${slug.padEnd(28)} ${meta.title}`);
  }
  console.log("\n用法: npx mland-cli add <slug> [--hospital=医院名称]\n");
}

function addSolution(slug: string, hospital?: string) {
  const meta = SOLUTIONS[slug];
  if (!meta) {
    console.error(`❌ 未知方案: ${slug}`);
    console.error("运行 npx mland-cli list 查看可用方案");
    process.exit(1);
  }

  const targetDir = path.join(process.cwd(), slug);
  if (fs.existsSync(targetDir)) {
    console.error(`❌ 目录已存在: ${targetDir}`);
    process.exit(1);
  }

  fs.mkdirSync(targetDir, { recursive: true });

  const envContent = `# ${meta.title}
# Generated by Mland CLI
${hospital ? `HOSPITAL_NAME=${hospital}\n` : ""}REDIS_URL=redis://localhost:6379
QDRANT_URL=http://localhost:6333
OPENAI_API_KEY=sk-your-key-here
HIS_API_ENDPOINT=https://his.internal/api
`;

  fs.writeFileSync(path.join(targetDir, ".env.example"), envContent);
  fs.writeFileSync(
    path.join(targetDir, "README.md"),
    `# ${meta.title}\n\n${hospital ? `> 定制部署：${hospital}\n\n` : ""}## 快速开始\n\n\`\`\`bash\ndocker compose up -d\n\`\`\`\n\n详见 [Mland 文档](https://github.com/MermaidLiu/Mland)\n`
  );

  console.log(`\n✅ 已创建方案: ${meta.title}`);
  if (hospital) console.log(`   医院: ${hospital}`);
  console.log(`   目录: ${targetDir}`);
  console.log(`\n下一步:`);
  console.log(`   cd ${slug}`);
  console.log(`   cp .env.example .env`);
  console.log(`   docker compose up -d\n`);
}

function deploySolution(slug: string, env: string) {
  console.log(`\n🚀 部署 ${slug} (${env})\n`);
  if (env === "k8s") {
    console.log(`kubectl apply -f packages/mland-deploy/k8s/${slug}/`);
    console.log(`\n⚠️  K8s 高可用部署为 Pro 版功能，联系 sales@mland.io\n`);
  } else {
    console.log(`cd ${slug} && docker compose up -d`);
  }
}

const { command, slug, args } = parseArgs(process.argv);

switch (command) {
  case "list":
    listSolutions();
    break;
  case "add":
    addSolution(slug, args.hospital);
    break;
  case "deploy":
    deploySolution(slug, args.env ?? "docker");
    break;
  default:
    console.log(`
Mland CLI — 企业级 AI 智能体部署工具

用法:
  npx mland-cli list
  npx mland-cli add pmp-agent --hospital=航天中心医院
  npx mland-cli add medical-translation --hospital=长庚医院
  npx mland-cli deploy pmp-agent --env=docker
  npx mland-cli deploy pmp-agent --env=k8s
`);
}
